version: '3.9'
services:
  backend_real_time_app:
    container_name: backend_real_time_app
    image: backend_real_time_img
    build:
      context: .
      dockerfile: ./infra/backend/Dockerfile
    volumes:
      - type: bind
        source: ./src/backend
        target: /app
    ports:
      - '3001:3001'
    environment:
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@db_real_time_app:27017/
    depends_on:
      - db_real_time_app
  db_real_time_app:
    container_name: db_real_time_app
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  frontend_real_time_app:
    container_name: frontend_real_time_app
    image: frontend_real_time_img
    build:
      context: .
      dockerfile: ./infra/frontend/Dockerfile
    volumes:
      - type: bind
        source: ./src/frontend
        target: /app
    ports:
      - '3000:3000'
    depends_on:
      - backend_real_time_app

volumes:
  mongodata: