version: '3.9'
services:
  backend_nest_app:
    container_name: backend_nest_app
    image: backend_nest_app
    build:
      context: .
      dockerfile: ../infra/backend/Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - '3001:3001'
    environment:
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - db_mongo_app
  db_mongo_app:
    container_name: db_mongo_app
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodata: